### ISSUE TITLE
Issues with unicode support?

### ISSUE THREAD

**Issue by Coaxial** [caronc/nzbget-subliminal#15]
I had this error when scanning my TV shows:

```
2015-10-10 23:58:00,900 - 7871 - ERROR - Unexpected error in provider 'podnapisi'
Traceback (most recent call last):
  File "/usr/src/nzbget-subliminal/Subliminal/subliminal/api.py", line 256, in download_best_subtitle
s
    provider_subtitles = provider.list_subtitles(video, provider_video_languages)
  File "/usr/src/nzbget-subliminal/Subliminal/subliminal/providers/podnapisi.py", line 314, in list_s
ubtitles
    episode=video.episode)]
  File "/usr/src/nzbget-subliminal/Subliminal/subliminal/providers/podnapisi.py", line 259, in query
    releases = [ str(releases.string.strip()), ]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc4' in position 0: ordinal not in range(
128)
```

I have files with accentuated characters in their filenames and it might be what triggers it.

**Comment by caronc** [comment]
I had a lot of troubles with this kind of thing (unicode and subliminal) in the past; but i had though i nailed it (I guess not).  I realize you might not want to share the whole error message publicly but it would greatly help me out.  The error messages your spitting are coming out of the subliminal core (what my script wraps around).

Please fire me an email to lead2gold -at- gmail . com with the full error.  I'd be also interested in the command you typed to get this error too (that will allow me to add it to my test environment here). 

Finally, if you run the same command with the __-D__ switch (__--debug__), it will also help reveal a lot of extra stuff that occurs before this error occurs. Also, what OS and version of Python are you using?

Thanks!

**Comment by f3bruary** [comment]
Traceback (most recent call last):
    File "/root/Subliminal/nzbget/ScriptBase.py", line 2398, in run
    exit_code = main_function(*args, **kwargs)
    File "/root/Subliminal/Subliminal.py", line 1709, in main
    use_nzbheaders=False,
    File "/root/Subliminal/Subliminal.py", line 1151, in subliminal_fetch
    srt_file_re, l.alpha3t, l.alpha3b, l.alpha2,
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58: ordinal not in range(128)

Happens with filenames containing an apostrophe. e.g. "Hi I'm f3bruary.mp4". Putting this here cause I think it's related.
