### ISSUE TITLE
Getting KeyError

### ISSUE THREAD

**Issue by PearsonFlyer** [caronc/nzbget-subliminal#36]
Just within the last few days, this error has started occurring multiple times during each subtitle check.  I haven't made any changes to my system. Running on Windows 10 (Creator's update).  It doesn't error on every single subtitle search, just 2-3 times on every check.

```
ERROR | Sun Sep 17 2017 14:26:42 | Subliminal: KeyError: None
-- | -- | --
INFO | Sun Sep 17 2017 14:26:42 | Subliminal: element_name = specs[element_id][1]
ERROR | Sun Sep 17 2017 14:26:42 | Subliminal: File "K:\Processing\NZBget_Scripts\Subliminal\enzyme\mkv.py", line 61, in _parse_seekhead
INFO | Sun Sep 17 2017 14:26:42 | Subliminal: self._parse_seekhead(seek_head, segment, stream, specs)
ERROR | Sun Sep 17 2017 14:26:42 | Subliminal: File "K:\Processing\NZBget_Scripts\Subliminal\enzyme\mkv.py", line 54, in __init__
INFO | Sun Sep 17 2017 14:26:42 | Subliminal: mkv = enzyme.MKV(f)
ERROR | Sun Sep 17 2017 14:26:42 | Subliminal: File "K:\Processing\NZBget_Scripts\Subliminal\subliminal\video.py", line 236, in scan_video
INFO | Sun Sep 17 2017 14:26:42 | Subliminal: video=video,
ERROR | Sun Sep 17 2017 14:26:42 | Subliminal: File "K:\Processing\NZBget_Scripts\Subliminal.py", line 1426, in subliminal_fetch
INFO | Sun Sep 17 2017 14:26:42 | Subliminal: use_nzbheaders=False,
ERROR | Sun Sep 17 2017 14:26:42 | Subliminal: File "K:\Processing\NZBget_Scripts\Subliminal.py", line 1864, in scheduler_main
INFO | Sun Sep 17 2017 14:26:42 | Subliminal: exit_code = main_function(*args, **kwargs)
ERROR | Sun Sep 17 2017 14:26:42 | Subliminal: File "K:\Processing\NZBget_Scripts\Subliminal\nzbget\ScriptBase.py", line 2935, in run
ERROR | Sun Sep 17 2017 14:26:42 | Subliminal: Traceback (most recent call last):
INFO | Sun Sep 17 2017 14:26:42 | Subliminal: Scanning video 'ShowName.S02E01.EpisodeName.mkv' in 'K:\\Media\\TV\\Elena of Avalor\\Season 02'
ERROR | Sun Sep 17 2017 14:26:42 | Subliminal: KeyError: None

```

**Comment by caronc** [comment]
Please give it another try and let me know; you'll need to check your copy out from the [master](https://github.com/caronc/nzbget-subliminal/archive/master.zip) branch.

**Comment by PearsonFlyer** [comment]
This solves the problem.  Thank you!
