### ISSUE TITLE
ERROR - Unexpected error in provider 'addic7ed'

### ISSUE THREAD

**Issue by dlmarston** [caronc/nzbget-subliminal#8]
hi Caronc,

I started getting this error message the other day. I have deleted my copy of your files and redownloaded them (as i wanted to make sure i was using your master branch again - i think you have moved back to developing on that instead of no-karma (?) i purely use addicted for my subtitles.

any thoughts on what is happening here?

edit: Python 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin

Error message:
2015-03-25 16:49:22,025 - 1112 - ERROR - Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "/Applications/nzbget-subliminal/Subliminal/subliminal/api.py", line 256, in download_best_subtitles
    provider_subtitles = provider.list_subtitles(video, provider_video_languages)
  File "/Applications/nzbget-subliminal/Subliminal/subliminal/providers/addic7ed.py", line 159, in list_subtitles
    return [s for s in self.query(video.series, video.season)
  File "/Applications/nzbget-subliminal/Subliminal/subliminal/providers/addic7ed.py", line 123, in query
    show_ids = self.get_show_ids()
  File "/Applications/nzbget-subliminal/Subliminal/dogpile/cache/region.py", line 1013, in decorate
    should_cache_fn)
  File "/Applications/nzbget-subliminal/Subliminal/dogpile/cache/region.py", line 640, in get_or_create
    async_creator) as value:
  File "/Applications/nzbget-subliminal/Subliminal/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/Applications/nzbget-subliminal/Subliminal/dogpile/core/dogpile.py", line 91, in _enter
    value = value_fn()
  File "/Applications/nzbget-subliminal/Subliminal/dogpile/cache/region.py", line 598, in get_value
    value = self.backend.get(key)
  File "/Applications/nzbget-subliminal/Subliminal/dogpile/cache/backends/file.py", line 218, in get
    with self._dbm_file(False) as dbm:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Applications/nzbget-subliminal/Subliminal/dogpile/cache/backends/file.py", line 213, in _dbm_file
    "w" if write else "r")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
ImportError: No module named gdbm

**Comment by dlmarston** [comment]
looks like another application (openplex) i recently installed, decided to install it's own version of python. i removed this, and installed python again using home-brew and it is all working again. phew!
